//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovikEntities3 : DbContext
    {
        public KursovikEntities3()
            : base("name=KursovikEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<EntranceEmployee> EntranceEmployee { get; set; }
        public virtual DbSet<ReceptionSchedule> ReceptionSchedule { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesChildren> ServicesChildren { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
